version: '3.4'
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.13.0
    ports:
      - 8080:8080
    restart: on-failure:0
    depends_on:
      - 't2v-transformers'
      - 'qna-transformers'
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QNA_INFERENCE_API: "http://qna-transformers:8080"
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,qna-transformers'
    volumes:
      - store:/var/lib/weaviate

  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-msmarco-distilbert-base-v2

  qna-transformers:
    image: semitechnologies/qna-transformers:bert-large-uncased-whole-word-masking-finetuned-squad

  server:
    image: parkerduckworth/foodtruck-recommender
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    links:
      - 'weaviate'
    depends_on:
      - 'weaviate'
    ports:
      - '9000:9000'
    environment:
      - GO_ENV=dev
    restart: unless-stopped

volumes:
  store:
